name: Test Documentation Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'infiniteflight/infiniteflight-docs'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install processmd
        run: yarn global add @infiniteflight/processmd
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_PAT }}
      - name: Build documentation
        run: processmd --no-output --no-uploadImages --inputDir=.